### ISSUE TITLE
LuaTeX needs \automatichyphenmode=2

### ISSUE THREAD

**Issue by gpoore** [gpoore/fvextra#14]
Line breaking needs to be customized for LuaTeX by setting `\automatichyphenmode=2`. Otherwise, a hyphen is automatically converted to a discretionary and thus there may be undesired line break locations.

See https://github.com/gpoore/minted/issues/263 for example. See LuaTeX manual around page 71 for details.

**Comment by maaattes** [comment]
Any news on this particular issue? I've been debugging my document for ages before finding this issue :( Right now I'm setting
```tex
\BeforeBeginEnvironment{minted}{\automatichyphenmode=2}
\AfterEndEnvironment{minted}{\automatichyphenmode=0}
```
in my preamble/LuaTeX class. is this an appropriate fix for the meantime?
