### ISSUE TITLE
Starred version of \SaveVerb

### ISSUE THREAD

**Issue by dr-scsi** [gpoore/fvextra#16]
Hi,

many thanks for this package.  The manual states that the macro `\SaveVerb` also has a starred version:

> 5.2 \SaveVerb  
> `\SaveVerb*[<options>]{<name>} <delim char or {> <text> <delim char or }>`  
> `\SaveVerb` is reimplemented so that it is equivalent to the reimplemented
`\Verb`. Like the new `\Verb`, it accepts `text` delimited by a pair of curly braces
`{...}`.

The starred version for `\Verb` means a shortcut for `showspaces`, but does this make sense when read in and save a portion of text?  Or am I missing something?

**Comment by muzimuzhi** [comment]
I didn't check the implementation, but from example below,
- The optional star after `\SaveVerb` has no effect, whether spaces are printed as `␣` is controlled by the optional star after `\UseVerb`.
- This behavior is inherited from `fancyvrb`.

```tex
\documentclass{article}
\usepackage{fancyvrb} % or fvextra

\begin{document}
\SaveVerb{Verb}|_verbatim verbatim_|
foo \UseVerb{Verb} bar \UseVerb*{Verb} baz

\SaveVerb*{Verb2}|_verbatim verbatim_|
foo \UseVerb{Verb2} bar \UseVerb*{Verb2} baz
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/187169372-264a2376-7456-46d8-8c2c-d12e01299b2d.png)

**Comment by dr-scsi** [comment]
@muzimuzhi - Thanks for your response and the code snippet.  That was more or less also my observation.  `fancyvrb` doesn't mention a starred version of `\SaveVerb`, so this can maybe be titled as a documentation bug in `fvextra`.  It should suffice to remove the `*` from the description of `\SaveVerb`.
