### ISSUE TITLE
LaTeX Error: Undefined color model `HTML'.

### ISSUE THREAD

**Issue by mcrone** [gpoore/fvextra#2]
Hey

I seem to be getting this error when using fvextra with minted. Tried a search on google and couldn't find anyone with a similar problem.

Would appreciate any help or advice on how to fix it.

**Comment by gpoore** [comment]
Try loading `xcolor`, which defines HTML. You are probably using `color`, which doesn't define it. The next version of `fvextra` will work with both `color` and `xcolor`...it will be out in a few days.

**Comment by mcrone** [comment]
Thank you! Sorry that was quite silly. I had presumed that it would bring up an error asking me to load xcolor instead...

**Comment by gpoore** [comment]
Usually `minted` takes care of loading `xcolor` when necessary. But `fvextra` interfered with the normal behavior. Everything should be back to normal with the next release.
