### ISSUE TITLE
`breaksymbolleft` is no-op in inline verbatims

### ISSUE THREAD

**Issue by Vftdan** [gpoore/fvextra#23]
## LaTeX header includes

```tex
\usepackage{fvextra}
\renewcommand{\VERB}{\Verb[commandchars=\\\{\},breaklines,breaksymbolleft={\tiny\ensuremath{\hookrightarrow}}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\},breaklines,breaksymbolleft={\tiny\ensuremath{\hookrightarrow}}}
```

## Expected behavior

The hookrightarrow symbol is added both in `\VERB` command and in `Highlighting` environment.

## Actual behavior

It only works in the environment, command version breaks lines but does not insert the symbol.

**Comment by gpoore** [comment]
This is intended. At the end of the `\Verb` documentation, under "Line breaking": "Break options that are only applicable to block text like a Verbatim environment do not have any effect. For example, breakindent and breaksymbol do nothing." The implementation for break symbols only works in a line-by-line verbatim context and cannot function within a normal paragraph. If you want some sort of break indicator in a normal paragraph, you could try something with `spacebreak`, but any symbols inserted that way will be inline, not in the margins.
