### ISSUE TITLE
Empty lines are wrongly highlighted with `numberblanklines=false`

### ISSUE THREAD

**Issue by muzimuzhi** [gpoore/fvextra#25]
Original report: https://github.com/gpoore/minted/issues/226

A `fvextra` example
```tex
\documentclass{article}
\usepackage{fvextra}
\usepackage{xcolor}

\begin{document}
\begin{Verbatim}[highlightlines=2,numberblanklines=false]
# line 1
# line 2

# line 4
\end{Verbatim}
\end{document}
```

![image](https://github.com/user-attachments/assets/f273dce8-c413-4d09-851c-c2c176914726)
The third line, which is empty, should not be highlighted.

One possible fix is to un-define each internal csname `FV@HighlightLine:\number\c@FancyVerbLine` for every highlighted line (this condition can be relaxed.) To escape the groups created by `\hbox` and still use the non-global scope, it seems such code has to be added to the end of `\FV@ListProcessLine@NoBreak` and `\FV@ListProcessLine@Break`, perhaps through a new hook `\FV@listProcessLine@PostHook`.

A demo
```tex
\documentclass{article}
\usepackage{fvextra}
\usepackage{xcolor}

\usepackage{xpatch}

\makeatletter
% a pair of new hooks
\xpretocmd{\FV@ListProcessLine@NoBreak}{\FV@ListProcessLine@PreHook}{}{\PatchFailed}
\xapptocmd{\FV@ListProcessLine@NoBreak}{\FV@ListProcessLine@PostHook}{}{\PatchFailed}
\xpretocmd{\FV@ListProcessLine@Break}{\FV@ListProcessLine@PreHook}{}{\PatchFailed}
\xapptocmd{\FV@ListProcessLine@Break}{\FV@ListProcessLine@PostHook}{}{\PatchFailed}

\let\FV@ListProcessLine@PreHook\@empty
\let\FV@ListProcessLine@PostHook\@empty

% is it safe to always undefine \FV@HighlightLine:<n> ?
\g@addto@macro\FV@ListProcessLine@PostHook{%
  \csundef{FV@HighlightLine:\number\c@FancyVerbLine}}

\fvset{breaklines=false} % update \FV@ListProcessLine
\makeatother

\begin{document}
\begin{Verbatim}[linenos, highlightlines={2},numberblanklines=false]
# line 1
# line 2

# line 4
\end{Verbatim}
\end{document}
```

![image](https://github.com/user-attachments/assets/38a0187c-d2f8-4619-9514-e7790b4e7e74)

**Comment by gpoore** [comment]
Undefining csname `FV@HighlightLine:\number\c@FancyVerbLine` would work to prevent the double-highlight, and that would definitely be an improvement.

I am concerned that options like `highlightlines` will be understood by users as referring to the lines in the .tex source (or included external source) rather than the line numbers that are displayed in the highlighted code. Dealing with that scenario would require patching a lot of `fancyvrb` to introduce a new counter, something like `FancyVerbRealLine`, that keeps track of the actual rather than displayed source line number.

**Comment by muzimuzhi** [comment]
Since its introduction in 2016 v1.1 (see https://github.com/gpoore/fvextra/commit/04170d1ab3407001f6230be5e46ba7c026a46cde and https://github.com/gpoore/fvextra/commit/534237a33e6c34b38f6f7d4fb626c53083466ab6), the doc of `highlightlines` has said

> The line numbers refer to the line numbers that `fancyvrb` would show if `numbers=left`, etc. They do not refer to original or actual line numbers before adjustment by `firstnumber`.

So dealing with "real" line numbers will need a new option or extended syntax in value of `highlightlines`. For example `highlight-real-lines` (hyphens to mark the difference) or `highlightlines={1, real(10-13), displayed(3)}`.

**Comment by gpoore** [comment]
This is fixed. Undefining csname `FV@HighlightLine:\number\c@FancyVerbLine` worked, but that had to be done conditionally within a patch to `\FV@StepLineNo` so that the logic for detecting the start/middle/end of a highlighted range functions correctly.

**Comment by muzimuzhi** [comment]
> ```tex
> If the previous line is at the end of a highlighted range, then |\let| |\FV@HighlightLine:<n>|
> to |\FV@Undefined| to prevent further highlighting. Otherwise, leave everything as-is since
> the blank line(s) are within a highlighted range.
> ```

Ha I missed that case. Thanks.
