### ISSUE TITLE
Font-related error when using Libertine

### ISSUE THREAD

**Issue by DaoWen** [gpoore/fvextra#4]
When using fvextra (via minted) with the [Libertine font package](https://www.ctan.org/pkg/libertine), I get the following error message:

    /usr/local/texlive/2016/texmf-dist/tex/latex/fvextra/fvextra.sty:562: Undefined control sequence \mdseries@tt.
    /usr/local/texlive/2016/texmf-dist/tex/latex/fvextra/fvextra.sty:562: leading text: ...FV@BreakSymbolIndentLeft}{\ttfamily xxxx}

The Libertine fonts depend on the mweights package for font configuration, but mweights uses the `\AtBeginDocument` command to delay some parts of the font setup.

It seems that the `\settowidth` command on line 562 is failing because the font configuration is not complete at the time that fvextra tries to compute these widths.

The following LaTeX document can be used to reproduce the error:

    \documentclass{article}
    \usepackage[T1]{fontenc}
    \usepackage{libertine}
    \usepackage{minted}
    \begin{document}
    \begin{minted}{c}
        int main(int argc, char *argv[]) {
            return 0;
        }
    \end{minted}
    \end{document}

**Comment by rojizo** [comment]
Previous version of mweights didn't raise this error

**Comment by gpoore** [comment]
This is fixed in v1.3. Everything equivalent to `\settowidth` is done immediately before use, not in the preamble during package loading.
